apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: 080266302756.dkr.ecr.us-east-2.amazonaws.com/flask_rest
        name: flask
        ports:
        - containerPort: 5000
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
              
---

apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 5000
  selector:
    app: flask

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: dns-01-production
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: flaskingress.abdelalitraining.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: flask-app
                port:
                  number: 8080
  tls:
    - hosts:
        - flaskingress.abdelalitraining.com
      secretName: flaskingress-abdelalitraining-com