apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-python-app-sa
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
