apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example-operator
    spec:
      serviceAccountName: example-operator
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: example-operator
      containers:
        - name: operator
          image: <your-registry>/example-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_PORT
              value: "8000"
            - name: HEALTH_PORT
              value: "8080"
          ports:
            - name: metrics
              containerPort: 8000
            - name: health
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
